<?php

namespace ContainerXlQpG9Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6tnPemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u6tnPem' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u6tnPem'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eval' => ['privates', '.errored..service_locator.u6tnPem.App\\Entity\\Evaluation', NULL, 'Cannot autowire service ".service_locator.u6tnPem": it references class "App\\Entity\\Evaluation" but no such service exists.'],
        ], [
            'eval' => 'App\\Entity\\Evaluation',
        ]);
    }
}
