<?php

namespace ContainerXlQpG9Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Te8pGamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.te8pGam' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.te8pGam'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'document' => ['privates', '.errored..service_locator.te8pGam.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.te8pGam": it references class "App\\Entity\\Document" but no such service exists.'],
        ], [
            'document' => 'App\\Entity\\Document',
        ]);
    }
}
