<?php

namespace ContainerXlQpG9Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EN4Ua7ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EN4Ua7Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EN4Ua7Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'idMa' => ['privates', '.errored..service_locator.EN4Ua7Z.App\\Entity\\AppHasMA', NULL, 'Cannot autowire service ".service_locator.EN4Ua7Z": it references class "App\\Entity\\AppHasMA" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.EN4Ua7Z.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EN4Ua7Z": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'idMa' => 'App\\Entity\\AppHasMA',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
