<?php

namespace ContainerXlQpG9Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NO7ExGfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nO7ExGf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nO7ExGf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator.nO7ExGf.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.nO7ExGf": it references class "App\\Entity\\Session" but no such service exists.'],
        ], [
            'session' => 'App\\Entity\\Session',
        ]);
    }
}
