<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IEzOZ4BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iEzOZ4B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iEzOZ4B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'app' => ['privates', '.errored..service_locator.iEzOZ4B.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.iEzOZ4B": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'app' => 'App\\Entity\\User',
        ]);
    }
}
