<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_83ddkwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._83ddkw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._83ddkw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator._83ddkw.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator._83ddkw": it references class "App\\Entity\\User" but no such service exists.'],
            'userInterface' => ['privates', '.errored..service_locator._83ddkw.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator._83ddkw": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'user' => 'App\\Entity\\User',
            'userInterface' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
