<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQacAVqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NQacAVq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQacAVq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'app' => ['privates', '.errored..service_locator.NQacAVq.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.NQacAVq": it references class "App\\Entity\\User" but no such service exists.'],
            'competence' => ['privates', '.errored..service_locator.NQacAVq.App\\Entity\\Competence', NULL, 'Cannot autowire service ".service_locator.NQacAVq": it references class "App\\Entity\\Competence" but no such service exists.'],
        ], [
            'app' => 'App\\Entity\\User',
            'competence' => 'App\\Entity\\Competence',
        ]);
    }
}
