<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qn2vLcoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qn2vLco' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qn2vLco'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.Qn2vLco.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.Qn2vLco": it references class "App\\Entity\\Document" but no such service exists.'],
        ], [
            'id' => 'App\\Entity\\Document',
        ]);
    }
}
