<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppHasMAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kSqul50.App\Entity\AppHasMA' shared service.
     *
     * @return \App\Entity\AppHasMA
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kSqul50": it references class "App\\Entity\\AppHasMA" but no such service exists.');
    }
}
