<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvaluationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u6tnPem.App\Entity\Evaluation' shared service.
     *
     * @return \App\Entity\Evaluation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.u6tnPem": it references class "App\\Entity\\Evaluation" but no such service exists.');
    }
}
