<?php

namespace ContainerNd5ZJAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nO7ExGf.App\Entity\Session' shared service.
     *
     * @return \App\Entity\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nO7ExGf": it references class "App\\Entity\\Session" but no such service exists.');
    }
}
