<?php

namespace ContainerTSY347i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Qn2vLco.App\Entity\Document' shared service.
     *
     * @return \App\Entity\Document
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Qn2vLco": it references class "App\\Entity\\Document" but no such service exists.');
    }
}
