<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgWe2Dg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgWe2Dg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZgWe2Dg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZgWe2Dg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZgWe2Dg\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZgWe2Dg',
    'container.build_id' => '665ff2ea',
    'container.build_time' => 1650835502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgWe2Dg');
