<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTSY347i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTSY347i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTSY347i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTSY347i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTSY347i\App_KernelDevDebugContainer([
    'container.build_hash' => 'TSY347i',
    'container.build_id' => 'a39381c5',
    'container.build_time' => 1644570258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTSY347i');
