<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBxydRk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBxydRk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWBxydRk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWBxydRk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWBxydRk\App_KernelDevDebugContainer([
    'container.build_hash' => 'WBxydRk',
    'container.build_id' => '6d583e57',
    'container.build_time' => 1650874563,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBxydRk');
